CREATE TABLE Users (
    id INT AUTO_INCREMENT PRIMARY KEY,
    username VARCHAR(255) NOT NULL UNIQUE,
    # email VARCHAR(255) NOT NULL UNIQUE,
    # birthday DATE NOT NULL,
    created_at TIMESTAMP DEFAULT NOW()
);